import { type Dictionary } from "./Dictionary";
import getAge from "../lib/get-age";

const age = getAge();

const en: Dictionary = {
  header: {
    forMoreInfoAccess: "For more information, visit",
    languages: "Languages",
    technologies: "Technologies",
    solutions: "Projects",
    repositories: "Repositories",
    contact: "Contact",
  },
  homepage: {
    metadata: {
      title: "Eduardo Dadalt - Full Stack Developer",
      description:
        "Full Stack Developer experienced in web, mobile, ERP, automation, and internal systems.",
    },
    pageOnConstruction: "Page under construction",
    myInfo: {
      hiMyNameIs: "Hi, my name is",
      role: "Full Stack Developer",
      location: "Itapema, Brazil · Remote or hybrid",
      availability: "Open to product, ERP, and automation opportunities",
      description: `I'm ${age}, studying Systems Analysis and Development at [FIAP](https://fiap.com.br), and I build web apps, mobile apps, and automations for real operational problems. I like working close to users, understanding the process, and turning that into software that is useful and maintainable.`,
      strengthsTitle: "What I bring to a team",
      strengths: [
        "Hands-on experience with ERP, customer service, support, and operational routines.",
        "End-to-end execution across frontend, backend, mobile, integrations, and automation.",
        "Ownership mindset: I understand the customer's pain and follow the solution until it works well.",
      ],
      stats: [
        { value: "4+", label: "years building software" },
        { value: "6", label: "WhatsApp accounts unified in one support hub" },
        { value: "Web + Mobile", label: "delivery across platforms" },
      ],
      experience: {
        title: "Experience",
        eyebrow: "Professional path",
        position: "Position",
        description: "Summary",
        highlights: "Highlights",
        jobs: [
          {
            company: "JR Sistemas",
            position: "Developer",
            dateBegin: "Oct 2021",
            dateEnd: "Present",
            description:
              "I build and maintain web and mobile systems for businesses that rely on ERP, customer support, and internal operations.",
            highlights: [
              "Helped migrate legacy modules to Flutter, building dashboards, reports, and registration forms.",
              "Built Node.js and Puppeteer automations to reduce manual work, including NFC-e downloads and support ticket checks.",
              "Worked on integrations with WhatsApp, databases, and operational systems used daily by customers.",
            ],
          },
          {
            company: "Voxy",
            position: "Technical Support",
            dateBegin: "Feb 2021",
            dateEnd: "Oct 2021",
            description:
              "I worked in customer service and technical support while creating small tools to speed up the team's routine.",
            highlights: [
              "Created a solution to fix fiscal files generated by the system.",
              "Developed a KDS integrated with TOTVS Chef for kitchen order tracking.",
              "Built operational and support context that now helps me develop more useful software for end users.",
            ],
          },
        ],
      },
      education: {
        title: "Education",
        institution: "Institution",
        situation: "Status",
        steps: [
          {
            institution: "FIAP",
            course: "Systems Analysis and Development",
            dateBegin: "Feb 2023",
            dateEnd: "Present",
            description: "In progress",
          },
          {
            institution: "IFRS - Canoas Campus",
            course: "Technical High School in Systems Analysis and Development",
            dateBegin: "Feb 2018",
            dateEnd: "Feb 2021",
            description:
              "Interrupted during the COVID-19 pandemic and my move to Itapema/SC. High school completed in 2022.",
          },
        ],
      },
    },
    programmingLanguage: {
      title: "Programming languages",
      description:
        "Languages I use or have used in projects, integrations, automation, and system maintenance.",
      iconOf: "Icon of",
    },
    technology: {
      title: "Technologies",
      description:
        "A stack focused on digital products, internal systems, databases, and integrations.",
    },
    solution: {
      title: "Projects and solutions",
      description:
        "A few deliveries that show how I turn operational needs into working products.",
      solutions: [
        {
          title: "Mobile ERP for small businesses",
          description: "Flutter · Dashboards · Forms",
          content:
            "Contributed to the beginning of the legacy system migration to Flutter by building registration screens, reports, and dashboards.",
          languagesAndTechnologies: ["/icons/technologies/flutter.svg"],
        },
        {
          title: "Waiter ordering app",
          description: "Flutter · Restaurant operations",
          content:
            "Worked on an app to view tables, place orders, and track order status, reducing friction between service and kitchen.",
          languagesAndTechnologies: ["/icons/technologies/flutter.svg"],
        },
        {
          title: "JR Sistemas company website",
          description: "React · Next.js",
          content:
            "Redesigned the company's website with React and Next.js, improving digital presence, offer clarity, and maintainability.",
          languagesAndTechnologies: [
            "/icons/technologies/react.svg",
            "/icons/technologies/next.js.svg",
          ],
        },
        {
          title: "WhatsApp-integrated support hub",
          description: "Node.js · Flutter · MySQL",
          content:
            "Built a support hub that unified 6 WhatsApp accounts, allowing the team to open tickets, track status, and talk to customers in one workflow.",
          languagesAndTechnologies: [
            "/icons/technologies/node.js.svg",
            "/icons/technologies/flutter.svg",
            "/icons/technologies/mysql.svg",
          ],
        },
        {
          title: "Mobile Kitchen Display System",
          description: "Node.js · Electron · React Native · MsSQL",
          content:
            "Created a TOTVS Chef integration for kitchen order management, allowing orders to be viewed, updated, and tracked in real time.",
          languagesAndTechnologies: [
            "/icons/technologies/node.js.svg",
            "/icons/technologies/electron.svg",
            "/icons/technologies/react.svg",
            "/icons/technologies/mssql.svg",
          ],
        },
        {
          title: "Process automation",
          description: "Node.js · Puppeteer",
          content:
            "Created automations for repetitive tasks, including downloading NFC-e documents from Santa Catarina and checking support ticket replies.",
          languagesAndTechnologies: [
            "/icons/technologies/node.js.svg",
            "/icons/technologies/puppeteer.svg",
          ],
        },
      ],
    },
    contact: {
      title: "Let's talk?",
      description:
        "If you need someone to build, maintain, or modernize web/mobile systems with operational awareness, I can help.",
      youCanContactMeVia: "You can contact me through",
      email: "Send email",
      linkedin: "LinkedIn",
      github: "GitHub",
    },
  },
  components: {
    cardLevel: {
      basic: "Basic",
      intermediate: "Intermediate",
      advanced: "Advanced",
    },
  },
};

export default en;
